/*
 * This source file was generated by the Gradle 'init' task
 */
package est.controle;

import est.controle.br.com.aulas.Aula;
import est.controle.br.com.aulas.Aula1;
import est.controle.br.com.aulas.Aula2;
import est.controle.br.com.aulas.Aula3;
import est.controle.br.com.aulas.Aula4;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        List<Aula> aulas = new ArrayList<>();
        Scanner scanner = new Scanner(System.in);
        aulas.add(new Aula1(scanner));
        aulas.add(new Aula2(scanner));
        aulas.add(new Aula3());
        aulas.add(new Aula4(scanner));
        for (Aula aula : aulas) {
            aula.execute();
        }
        scanner.close();
    }
}
